[workspace]
semver_check = false
git_release_enable = true
changelog_update = true
git_tag_name = "v{{ version }}"

[changelog]
commit_parsers = [
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^style", skip = true },
    { message = "^build", skip = true },
    { message = "^docs\\(ci\\)", skip = true },
    { message = "^Merge", skip = true },
    { message = "^docs", group = "Documentation" },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactored" },
    { message = "^test", group = "Testing" },
]
