//! Integration tests for C14N against xmllint reference outputs.
//!
//! Reference outputs generated by: `xmllint --c14n <file>` and `xmllint --exc-c14n <file>`
//! using libxml2 (system xmllint). These are the authoritative C14N implementations.

use xml_sec::c14n::{canonicalize_xml, C14nAlgorithm, C14nMode};

// ─── Helpers ────────────────────────────────────────────────────────────────

fn assert_c14n(xml: &[u8], mode: C14nMode, with_comments: bool, expected: &str) {
    let algo = C14nAlgorithm::new(mode, with_comments);
    let result = canonicalize_xml(xml, &algo).expect("canonicalize failed");
    let result_str = String::from_utf8(result).expect("invalid utf8");
    assert_eq!(
        result_str, expected,
        "\n--- GOT ---\n{result_str}\n--- EXPECTED ---\n{expected}"
    );
}

fn assert_exc_c14n(xml: &[u8], prefix_list: &str, expected: &str) {
    let algo = C14nAlgorithm::new(C14nMode::Exclusive1_0, false).with_prefix_list(prefix_list);
    let result = canonicalize_xml(xml, &algo).expect("canonicalize failed");
    let result_str = String::from_utf8(result).expect("invalid utf8");
    assert_eq!(
        result_str, expected,
        "\n--- GOT ---\n{result_str}\n--- EXPECTED ---\n{expected}"
    );
}

// ─── Simple namespace document (inclusive) ──────────────────────────────────
// Reference output verified against: xmllint --c14n

const SIMPLE_NS_XML: &[u8] =
    br#"<root xmlns:z="http://z.com" xmlns:a="http://a.com" xmlns="http://default.com" b="2" a="1">
  <a:child z:attr="val" plain="yes">
    <inner/>
  </a:child>
  <z:other xmlns:a="http://a-override.com"/>
</root>"#;

#[test]
fn simple_ns_inclusive() {
    // Reference from xmllint --c14n:
    // - ns decls sorted: xmlns= first, then xmlns:a, xmlns:z
    // - attrs sorted: a before b (no namespace, lexicographic)
    // - child: ns inherited, not redeclared; attrs sorted: plain, z:attr
    // - z:other: xmlns:a overridden, must redeclare
    assert_c14n(
        SIMPLE_NS_XML,
        C14nMode::Inclusive1_0,
        false,
        concat!(
            r#"<root xmlns="http://default.com" xmlns:a="http://a.com" xmlns:z="http://z.com" a="1" b="2">"#,
            "\n",
            r#"  <a:child plain="yes" z:attr="val">"#,
            "\n",
            r#"    <inner></inner>"#,
            "\n",
            r#"  </a:child>"#,
            "\n",
            r#"  <z:other xmlns:a="http://a-override.com"></z:other>"#,
            "\n",
            r#"</root>"#,
        ),
    );
}

#[test]
fn simple_ns_exclusive() {
    // Reference from xmllint --exc-c14n:
    // - root: only xmlns= (default ns used by root tag)
    // - a:child: xmlns:a, xmlns:z (used by a: prefix and z:attr)
    // - inner: no ns (no prefix used, inherits default from parent)
    // - z:other: xmlns:z only (a: not used by z:other)
    assert_exc_c14n(
        SIMPLE_NS_XML,
        "",
        concat!(
            r#"<root xmlns="http://default.com" a="1" b="2">"#,
            "\n",
            r#"  <a:child xmlns:a="http://a.com" xmlns:z="http://z.com" plain="yes" z:attr="val">"#,
            "\n",
            r#"    <inner></inner>"#,
            "\n",
            r#"  </a:child>"#,
            "\n",
            r#"  <z:other xmlns:z="http://z.com"></z:other>"#,
            "\n",
            r#"</root>"#,
        ),
    );
}

// ─── Merlin-like document ───────────────────────────────────────────────────
// Structure from merlin-c14n-three/signature.xml (data portion only)
// Reference from xmllint --c14n / --exc-c14n

const MERLIN_DATA_XML: &[u8] = br#"<?xml version="1.0" encoding="UTF-8"?>
<foo:Root xmlns:bar="http://example.org/bar" xmlns:baz="http://example.org/baz" xmlns:foo="http://example.org/foo" xmlns="http://example.org/" xml:lang="en-ie">
  <bar:Something>
    <foo:Nothing>
      <foo:Something>
        <bar:Something>
          <foo:Something>
            <foo:Nothing>
              <foo:Something>
                <baz:Something />
              </foo:Something>
            </foo:Nothing>
          </foo:Something>
        </bar:Something>
      </foo:Something>
    </foo:Nothing>
  </bar:Something>
</foo:Root>"#;

#[test]
fn merlin_data_inclusive() {
    // All 4 ns prefixes + default ns + xml:lang on root.
    // Inner elements inherit everything, no redeclarations.
    assert_c14n(
        MERLIN_DATA_XML,
        C14nMode::Inclusive1_0,
        false,
        concat!(
            r#"<foo:Root xmlns="http://example.org/" xmlns:bar="http://example.org/bar" xmlns:baz="http://example.org/baz" xmlns:foo="http://example.org/foo" xml:lang="en-ie">"#,
            "\n",
            "  <bar:Something>\n",
            "    <foo:Nothing>\n",
            "      <foo:Something>\n",
            "        <bar:Something>\n",
            "          <foo:Something>\n",
            "            <foo:Nothing>\n",
            "              <foo:Something>\n",
            "                <baz:Something></baz:Something>\n",
            "              </foo:Something>\n",
            "            </foo:Nothing>\n",
            "          </foo:Something>\n",
            "        </bar:Something>\n",
            "      </foo:Something>\n",
            "    </foo:Nothing>\n",
            "  </bar:Something>\n",
            "</foo:Root>",
        ),
    );
}

#[test]
fn merlin_data_exclusive() {
    // Exclusive: each element only declares what it visibly uses.
    // foo:Root uses foo: prefix → xmlns:foo
    // xml:lang is an attribute, always present on root
    // bar:Something uses bar: → xmlns:bar
    // foo:Nothing uses foo: → already rendered by parent? No — exc mode
    //   tracks per output ancestor, foo:Root rendered foo:, so foo:Nothing inherits
    // baz:Something uses baz: → xmlns:baz
    // Default ns (xmlns="http://example.org/") not used by any element prefix → NOT rendered
    assert_exc_c14n(
        MERLIN_DATA_XML,
        "",
        concat!(
            r#"<foo:Root xmlns:foo="http://example.org/foo" xml:lang="en-ie">"#,
            "\n",
            r#"  <bar:Something xmlns:bar="http://example.org/bar">"#,
            "\n",
            "    <foo:Nothing>\n",
            "      <foo:Something>\n",
            "        <bar:Something>\n",
            "          <foo:Something>\n",
            "            <foo:Nothing>\n",
            "              <foo:Something>\n",
            r#"                <baz:Something xmlns:baz="http://example.org/baz"></baz:Something>"#,
            "\n",
            "              </foo:Something>\n",
            "            </foo:Nothing>\n",
            "          </foo:Something>\n",
            "        </bar:Something>\n",
            "      </foo:Something>\n",
            "    </foo:Nothing>\n",
            "  </bar:Something>\n",
            "</foo:Root>",
        ),
    );
}

// ─── Attribute sorting with namespaced attributes ───────────────────────────
// Reference from xmllint --c14n

const ATTR_SORT_XML: &[u8] = br#"<root xmlns:ns2="http://ns2" xmlns:ns1="http://ns1">
  <elem ns2:b="2" ns1:a="1" ns2:a="3" ns1:b="4" plain="5"/>
</root>"#;

#[test]
fn attr_sort_inclusive() {
    // Attributes sorted by (namespace-uri, local-name):
    // - plain (no ns, "") → first
    // - ns1:a (http://ns1, a)
    // - ns1:b (http://ns1, b)
    // - ns2:a (http://ns2, a)
    // - ns2:b (http://ns2, b)
    assert_c14n(
        ATTR_SORT_XML,
        C14nMode::Inclusive1_0,
        false,
        concat!(
            r#"<root xmlns:ns1="http://ns1" xmlns:ns2="http://ns2">"#,
            "\n",
            r#"  <elem plain="5" ns1:a="1" ns1:b="4" ns2:a="3" ns2:b="2"></elem>"#,
            "\n",
            "</root>",
        ),
    );
}

#[test]
fn attr_sort_exclusive() {
    // In exclusive mode: root uses no ns → no decls on root.
    // elem uses ns1: and ns2: → declares both.
    assert_exc_c14n(
        ATTR_SORT_XML,
        "",
        concat!(
            "<root>\n",
            r#"  <elem xmlns:ns1="http://ns1" xmlns:ns2="http://ns2" plain="5" ns1:a="1" ns1:b="4" ns2:a="3" ns2:b="2"></elem>"#,
            "\n",
            "</root>",
        ),
    );
}

// ─── Comments and Processing Instructions ───────────────────────────────────

const COMMENTS_PI_XML: &[u8] = b"<!-- doc-level comment -->\n<?target data?>\n<root>\n  <!-- inner comment -->\n  <child></child>\n</root>\n<!-- trailing comment -->";

#[test]
fn comments_stripped() {
    // Comments are stripped entirely. PI is first output, no leading \n.
    // Trailing comment also stripped, no trailing \n.
    // The whitespace text node between stripped comment and PI is at
    // document level → ignored by C14N.
    assert_c14n(
        COMMENTS_PI_XML,
        C14nMode::Inclusive1_0,
        false,
        concat!(
            "<?target data?>\n",
            "<root>\n",
            "  \n",
            "  <child></child>\n",
            "</root>",
        ),
    );
}

#[test]
fn comments_preserved() {
    assert_c14n(
        COMMENTS_PI_XML,
        C14nMode::Inclusive1_0,
        true,
        concat!(
            "<!-- doc-level comment -->\n<?target data?>\n",
            "<root>\n",
            "  <!-- inner comment -->\n",
            "  <child></child>\n",
            "</root>\n<!-- trailing comment -->",
        ),
    );
}

// ─── Idempotency ────────────────────────────────────────────────────────────

#[test]
fn idempotency_inclusive() {
    let algo = C14nAlgorithm::new(C14nMode::Inclusive1_0, false);
    let pass1 = canonicalize_xml(MERLIN_DATA_XML, &algo).expect("pass1");
    let pass2 = canonicalize_xml(&pass1, &algo).expect("pass2");
    assert_eq!(pass1, pass2, "C14N must be idempotent");
}

#[test]
fn idempotency_exclusive() {
    let algo = C14nAlgorithm::new(C14nMode::Exclusive1_0, false);
    let pass1 = canonicalize_xml(MERLIN_DATA_XML, &algo).expect("pass1");
    let pass2 = canonicalize_xml(&pass1, &algo).expect("pass2");
    assert_eq!(pass1, pass2, "Exclusive C14N must be idempotent");
}

// ─── Empty document edge case ───────────────────────────────────────────────

#[test]
fn minimal_document() {
    assert_c14n(b"<r/>", C14nMode::Inclusive1_0, false, "<r></r>");
}

#[test]
fn cdata_flattened() {
    // CDATA sections should be replaced with escaped text content.
    assert_c14n(
        b"<r><![CDATA[a < b & c]]></r>",
        C14nMode::Inclusive1_0,
        false,
        "<r>a &lt; b &amp; c</r>",
    );
}

// ─── Prefix aliasing (multiple prefixes for same URI) ───────────────────────

#[test]
fn aliased_prefixes_exclusive() {
    // Two prefixes bound to the same URI. Each element/attribute must preserve
    // the lexical prefix actually used in the source, not an arbitrary one
    // returned by lookup_prefix().
    let xml = br#"<root xmlns:a="http://same" xmlns:b="http://same"><b:child a:x="1"/></root>"#;
    assert_exc_c14n(
        xml,
        "",
        concat!(
            "<root>",
            r#"<b:child xmlns:a="http://same" xmlns:b="http://same" a:x="1"></b:child>"#,
            "</root>",
        ),
    );
}

#[test]
fn aliased_prefixes_inclusive() {
    let xml = br#"<root xmlns:a="http://same" xmlns:b="http://same"><b:child a:x="1"/></root>"#;
    assert_c14n(
        xml,
        C14nMode::Inclusive1_0,
        false,
        concat!(
            r#"<root xmlns:a="http://same" xmlns:b="http://same">"#,
            r#"<b:child a:x="1"></b:child>"#,
            "</root>",
        ),
    );
}

// ─── Default namespace undeclaration ────────────────────────────────────────

#[test]
fn default_ns_undeclaration() {
    let xml = br#"<root xmlns="http://example.com"><child xmlns=""/></root>"#;
    assert_c14n(
        xml,
        C14nMode::Inclusive1_0,
        false,
        r#"<root xmlns="http://example.com"><child xmlns=""></child></root>"#,
    );
}
