#!/usr/bin/env bash
set -euo pipefail

readonly SOURCE_DIR="${LIBXSLT_SOURCE_DIR:-}"
readonly PINNED_COMMIT="35323d6a15f6e63c9919ddbc0abe64c90a0dd88a"
readonly DESTINATION="crates/xml-sec-xslt/tests/fixtures/libxslt-1.1.45"
readonly RUNTEST_SUITES=(
  REC2
  REC
  general
  encoding
  documents
  numbers
  keys
  namespaces
  extensions
  reports
  exslt/common
  exslt/crypto
  exslt/date
  exslt/dynamic
  exslt/functions
  exslt/math
  exslt/saxon
  exslt/sets
  exslt/strings
  plugins
)

if [[ -z "$SOURCE_DIR" ]] || ! git -C "$SOURCE_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "LIBXSLT_SOURCE_DIR must point to a libxslt checkout" >&2
  exit 2
fi
source_commit="$(git -C "$SOURCE_DIR" rev-parse HEAD)"
if [[ "$source_commit" != "$PINNED_COMMIT" ]]; then
  echo "libxslt checkout must be at pinned commit $PINNED_COMMIT" >&2
  exit 2
fi

stage="$(mktemp -d)"
donor_stage="$(mktemp -d)"
trap 'rm -rf "$stage" "$donor_stage"' EXIT
mkdir -p "$stage/upstream"

# Archive the pinned commit rather than copying the donor worktree. Autotools
# and local builds leave ignored Makefile.in and generated data behind even in
# a git-clean checkout; those files are not part of the upstream source corpus.
git -C "$SOURCE_DIR" archive --format=tar "$PINNED_COMMIT" tests Copyright \
  | tar -xf - -C "$donor_stage"
readonly DONOR_DIR="$donor_stage"

# Keep the complete upstream test tree. Besides direct input/output triplets,
# stylesheets depend on sibling modules, DTDs, entities, images, and generated
# suite metadata. Vendoring only files referenced by currently passing cases
# silently changes the corpus whenever engine coverage grows.
cp -R "$DONOR_DIR/tests/." "$stage/upstream/tests/"
cp "$DONOR_DIR/Copyright" "$stage/LICENSE"

manifest="$stage/cases.tsv"
printf 'suite\tstylesheet\tsource\toutput\terrors\tkind\n' > "$manifest"

for suite in "${RUNTEST_SUITES[@]}"; do
  suite_dir="$DONOR_DIR/tests/$suite"
  [[ -d "$suite_dir" ]] || continue
  while IFS= read -r stylesheet; do
    stem="${stylesheet%.xsl}"
    source="$stem.xml"
    [[ -f "$source" ]] || continue
    relative_stem="${stem#"$DONOR_DIR/tests/"}"
    output=""
    errors=""
    [[ -f "$stem.out" ]] && output="$relative_stem.out"
    [[ -f "$stem.err" ]] && errors="$relative_stem.err"
    printf 'runtest\t%s.xsl\t%s.xml\t%s\t%s\ttransform\n' \
      "$relative_stem" "$relative_stem" "$output" "$errors" >> "$manifest"
  done < <(find "$suite_dir" -maxdepth 1 -type f -name '*.xsl' | LC_ALL=C sort)
done

# runtest.c executes standalone stylesheet documents separately. The XML file
# is both stylesheet and source; the xml-stylesheet PI resolves the module.
while IFS= read -r source; do
  stem="${source%.xml}"
  relative_stem="${stem#"$DONOR_DIR/tests/"}"
  output=""
  errors=""
  [[ -f "$stem.stand.out" ]] && output="$relative_stem.stand.out"
  [[ -f "$stem.stand.err" ]] && errors="$relative_stem.stand.err"
  printf 'runtest-standalone\t%s.xml\t%s.xml\t%s\t%s\tstandalone\n' \
    "$relative_stem" "$relative_stem" "$output" "$errors" >> "$manifest"
done < <(find "$DONOR_DIR/tests/REC" -maxdepth 1 -type f -name 'stand*.xml' | LC_ALL=C sort)

# XSLTMark's Makefile drives every committed .out target. Three database inputs
# are deterministically generated by its own dbgen.pl, exactly as upstream does.
for size in 100 1000 10000; do
  perl "$DONOR_DIR/tests/XSLTMark/dbgen.pl" "$size" \
    > "$stage/upstream/tests/XSLTMark/db$size.xml"
done
while IFS= read -r output; do
  name="$(basename "$output" .out)"
  stylesheet="$name.xsl"
  source="$name.xml"
  case "$name" in
    alphabetize|avts|creation|dbtail|decoy|encrypt|functions|patterns|prettyprint)
      source="db100.xml"
      ;;
    identity|stringsort)
      source="db1000.xml"
      ;;
    dbonerow)
      source="db10000.xml"
      ;;
    attsets|chart|total)
      source="chart.xml"
      ;;
    backwards|game)
      source="game.xml"
      ;;
    reverser)
      source="gettysburg.xml"
      ;;
    summarize)
      source="queens.xsl"
      ;;
    xslbench2|xslbench3)
      source="xslbenchdream.xml"
      ;;
    breadth|depth)
      stylesheet="find.xsl"
      ;;
  esac
  printf 'xsltmark\tXSLTMark/%s\tXSLTMark/%s\tXSLTMark/%s.out\t\ttransform\n' \
    "$stylesheet" "$source" "$name" >> "$manifest"
done < <(find "$DONOR_DIR/tests/XSLTMark" -maxdepth 1 -type f -name '*.out' | LC_ALL=C sort)

# DocBook runs each source document through the HTML, XHTML, and FO roots.
while IFS= read -r source; do
  name="$(basename "$source" .xml)"
  for format in html xhtml fo; do
    extension="$format"
    [[ "$format" == "fo" ]] && extension="fo"
    output="$DONOR_DIR/tests/docbook/result/$format/$name.$extension"
    [[ -f "$output" ]] || continue
    printf 'docbook\tdocbook/%s/docbook.xsl\tdocbook/test/%s.xml\tdocbook/result/%s/%s.%s\t\ttransform\n' \
      "$format" "$name" "$format" "$name" "$extension" >> "$manifest"
  done
done < <(find "$DONOR_DIR/tests/docbook/test" -maxdepth 1 -type f -name '*.xml' | LC_ALL=C sort)

printf 'multiple\tmultiple/dict.xsl\tmultiple/dict.xml\tmultiple/result.xml\t\tmultiple-output\n' \
  >> "$manifest"
printf 'xinclude\txinclude/e.xsl\txinclude/e.xml\txinclude/normal.out\t\ttransform\n' \
  >> "$manifest"
printf 'xinclude\txinclude/e.xsl\txinclude/e.xml\txinclude/xinclude.out\t\txinclude\n' \
  >> "$manifest"
printf 'xmlspec\txmlspec/REC-xml-2e.xsl\txmlspec/REC-xml-20001006.xml\txmlspec/REC-xml-20001006.html\t\ttransform\n' \
  >> "$manifest"
printf 'xmlspec\txmlspec/REC-xml-2e.xsl\txmlspec/REC-xml-20001006.xml\txmlspec/REC-xml-20001006-review.html\t\txmlspec-review\n' \
  >> "$manifest"

# Every vendored path is hashed so --check detects omissions and byte drift,
# including helper files that are not top-level test entry points.
(
  cd "$stage/upstream"
  find tests -type f -print0 \
    | LC_ALL=C sort -z \
    | xargs -0 shasum -a 256
) > "$stage/files.sha256"

cat > "$stage/README.md" <<'EOF'
# libxslt 1.1.45 oracle corpus

`upstream/tests` is the complete test tree from libxslt 1.1.45 commit
`35323d6a15f6e63c9919ddbc0abe64c90a0dd88a`, not a curated fixture subset.
It includes the core `runtest.c` suites, REC/REC2, EXSLT, XSLTMark, DocBook,
multiple-output, XInclude, xmlspec, fuzz inputs, dependencies, and golden files.

`cases.tsv` is generated from the suite directories registered by `runtest.c`.
`files.sha256` accounts for every upstream file and makes accidental corpus
truncation or fixture rewriting visible in CI. The original MIT license is in
`LICENSE`.
EOF

if [[ "${1:-}" == "--check" ]]; then
  diff -ru "$DESTINATION" "$stage"
else
  rm -rf "$DESTINATION"
  mkdir -p "$DESTINATION"
  cp -R "$stage/." "$DESTINATION/"
fi
